using 'main.bicep'

param workload = 'ticketing'
param environment = 'dev'
param location = 'swedencentral'
param owner = 'hackathon-team'
param costCenter = 'hackathon'
param vnetAddressPrefix = '10.10.0.0/16'
param appSubnetPrefix = '10.10.1.0/24'
param privateEndpointSubnetPrefix = '10.10.2.0/24'
param deployScriptSubnetPrefix = '10.10.3.0/24'
